apiVersion: v2
name: zebra-sdlc-rollup
version: __VERSION__
description: A fixed release of all zebra services
maintainers:
  - name: Andi Hyson
    email: andi.hyson@dotmatics.com
dependencies:
  - name: zebra-fe-store
    version: 0.2.9-release-25-09-0-5410-1
    repository: '@helm-virtual'
  - name: sciplat-fe-app-shell
    version: 0.3.0-release-25-09-0-5410-1
    repository: '@helm-virtual'
  - name: sciplat-fe-shell-navigation
    version: 0.3.2-release-25-09-0-5410-1
    repository: '@helm-virtual'
  - name: sciplat-svc-ingress-context
    version: 0.1.1-release-25-09-0-5410-1
    repository: '@helm-virtual'
  - name: sciplat-svc-module
    version: 0.1.0-release-25-09-0-5410-1
    repository: '@helm-virtual'
  - name: zebra-fe-module-system-settings
    version: 0.3.9-release-25-09-0-5410-1
    repository: '@helm-virtual'
  - name: zebra-keycloak
    version: 0.2.1-release-25-09-0-5410-1
    repository: '@helm-virtual'
  - name: zebra-openpolicyagent
    version: 0.3.2-release-25-09-0-5410-1
    repository: '@helm-virtual'
  - name: zebra-svc-system-settings
    version: 0.2.1-release-25-09-0-5410-1
    repository: '@helm-virtual'
  - name: zebra-fe-module-user-settings
    version: 0.0.1-release-25-09-0-5410-1
    repository: '@helm-virtual'
  - name: datacore-svc-backend
    version: 1.15.0-release-25-09-0-17220063287-1-952fb0ed
    repository: '@helm-virtual'
  - name: sciplat-svc-audit
    version: 0.1.0-release-25-09-0-5410-1
    repository: '@helm-virtual'
  - name: sciplat-svc-api-key
    version: 0.1.0-release-25-09-0-5410-1
    repository: '@helm-virtual'
  - name: sciplat-svc-realm-manager
    version: 0.1.3-release-25-09-0-5410-1
    repository: '@helm-virtual'
  - name: sciplat-svc-authz
    version: 0.1.4-release-25-09-0-5410-1
    repository: '@helm-virtual'
  - name: sciplat-svc-databricks-manager
    version: 0.2.5-release-25-09-0-5410-1
    repository: '@helm-virtual'
  - name: sciplat-fe-luma-admin-shell
    version: 0.0.2-release-25-09-0-5410-4
    repository: '@helm-virtual'
  - name: sciplat-fe-module-luma-admin
    version: 0.3.11-release-25-09-0-5410-4
    repository: '@helm-virtual'
  - name: datacore-frontend
    version: 1.14.0-release-25-08-0-16591677748-1-df58f945
    repository: '@helm-virtual'
  - name: luma-registration
    version: 0.0.1-release-25-09-0-3648-1
    repository: '@helm-virtual'
  - name: luma-mixologist-backend
    version: 0.9.0-release-25-09-0-4085-1
    repository: '@helm-virtual'
  - name: bioglyph-fe
    version: 0.0.1-release-25-06-0-684b740c
    repository: '@helm-virtual'
  - name: luma-svc-if-module
    version: 0.0.1-release-25-09-0-492-1
    repository: '@helm-virtual'
  - name: luma-ops-application-resources
    version: 0.1.0-21319a1f
    repository: '@helm-virtual'
  - name: luma-app-observer
    version: 0.0.1-release-25-09-0-37-1
    repository: '@helm-virtual'
  - name: luma-agent
    version: 0.0.1-release-25-09-0-167-1
    repository: '@helm-virtual'
    condition: luma-agent.enabled
