apiVersion: v2
name: zebra-sdlc-rollup
version: __VERSION__
description: A fixed release of all zebra services
maintainers:
  - name: Andi Hyson
    email: andi.hyson@dotmatics.com
dependencies:
  - name: zebra-fe-store
    version: 0.2.9-6154-1
    repository: '@helm-virtual'
  - name: sciplat-fe-app-shell
    version: 0.3.0-6154-1
    repository: '@helm-virtual'
  - name: sciplat-fe-shell-navigation
    version: 0.3.2-6154-1
    repository: '@helm-virtual'
  - name: sciplat-svc-ingress-context
    version: 0.1.1-6139-1
    repository: '@helm-virtual'
  - name: sciplat-svc-module
    version: 0.1.0-6139-1
    repository: '@helm-virtual'
  - name: zebra-fe-module-system-settings
    version: 0.3.9-6154-1
    repository: '@helm-virtual'
  - name: zebra-keycloak
    version: 0.2.1-6139-1
    repository: '@helm-virtual'
  - name: zebra-openpolicyagent
    version: 0.3.2-6131-1
    repository: '@helm-virtual'
  - name: zebra-svc-system-settings
    version: 0.2.1-6139-1
    repository: '@helm-virtual'
  - name: zebra-fe-module-user-settings
    version: 0.0.1-6154-1
    repository: '@helm-virtual'
  - name: datacore-svc-backend
    version: 1.17.0-18718155475-1-030eb51c
    repository: '@helm-virtual'
  - name: sciplat-svc-audit
    version: 0.1.0-6139-1
    repository: '@helm-virtual'
  - name: sciplat-svc-api-key
    version: 0.1.0-6139-1
    repository: '@helm-virtual'
  - name: sciplat-svc-realm-manager
    version: 0.1.4-6139-1
    repository: '@helm-virtual'
  - name: sciplat-svc-authz
    version: 0.2.0-6139-1
    repository: '@helm-virtual'
  - name: sciplat-svc-databricks-manager
    version: 0.3.0-6139-1
    repository: '@helm-virtual'
  - name: sciplat-fe-luma-admin-shell
    version: 0.0.2-5994-1
    repository: '@helm-virtual'
  - name: sciplat-fe-module-luma-admin
    version: 0.3.12-5994-1
    repository: '@helm-virtual'
  - name: luma-registration
    version: 0.0.1-4310-1
    repository: '@helm-virtual'
  - name: datacore-frontend
    version: 1.17.0-18718155475-1-030eb51c
    repository: '@helm-virtual'
  - name: bioglyph-fe
    version: 0.0.1-f5aceb09
    repository: '@helm-virtual'
  - name: luma-mixologist-backend
    version: 0.9.0-5032-1
    repository: '@helm-virtual'
  - name: luma-svc-if-module
    version: 0.0.1-717-1
    repository: '@helm-virtual'
  - name: luma-ops-application-resources
    version: 0.1.0-482b512d
    repository: '@helm-virtual'
  - name: app-service
    version: 1.17.0-18688316087-1-4d831c4e
    repository: '@helm-virtual'
    condition: app-service.enabled
  - name: luma-app-observer
    version: 0.0.1-36-1
    repository: '@helm-virtual'
  - name: luma-agent
    version: 0.0.3-235-1
    repository: '@helm-virtual'
    condition: luma-agent.enabled
  - name: luma-ontology
    version: 0.0.1-93-1
    repository: '@helm-virtual'
    condition: luma-ontology.enabled
  - name: luma-app-library
    version: 1.0.0-44-1
    repository: '@helm-virtual'
