apiVersion: v2
name: zebra-sdlc-rollup
version: __VERSION__
description: A fixed release of all zebra services
maintainers:
  - name: Andi Hyson
    email: andi.hyson@dotmatics.com
dependencies:
  - name: zebra-fe-store
    version: 0.2.9-6761-1
    repository: '@helm-virtual'
  - name: sciplat-fe-app-shell
    version: 0.3.0-6761-1
    repository: '@helm-virtual'
  - name: sciplat-fe-shell-navigation
    version: 0.3.2-6761-1
    repository: '@helm-virtual'
  - name: sciplat-svc-ingress-context
    version: 0.1.1-6761-1
    repository: '@helm-virtual'
  - name: sciplat-svc-module
    version: 0.1.0-6761-1
    repository: '@helm-virtual'
  - name: zebra-fe-module-system-settings
    version: 0.4.0-6761-1
    repository: '@helm-virtual'
  - name: zebra-keycloak
    version: 0.2.1-6761-1
    repository: '@helm-virtual'
  - name: zebra-openpolicyagent
    version: 0.3.2-6761-1
    repository: '@helm-virtual'
  - name: zebra-svc-system-settings
    version: 0.2.1-6761-1
    repository: '@helm-virtual'
  - name: zebra-fe-module-user-settings
    version: 0.0.1-6761-1
    repository: '@helm-virtual'
  - name: datacore-svc-backend
    version: 1.17.0-19762030742-1-f940ae5e
    repository: '@helm-virtual'
  - name: sciplat-svc-audit
    version: 0.1.0-6761-1
    repository: '@helm-virtual'
  - name: sciplat-svc-api-key
    version: 0.1.0-6761-1
    repository: '@helm-virtual'
  - name: sciplat-svc-realm-manager
    version: 0.1.10-6761-1
    repository: '@helm-virtual'
  - name: sciplat-svc-authz
    version: 0.2.0-6761-1
    repository: '@helm-virtual'
  - name: sciplat-svc-databricks-manager
    version: 0.3.0-6761-1
    repository: '@helm-virtual'
  - name: sciplat-fe-luma-admin-shell
    version: 0.0.2-6761-1
    repository: '@helm-virtual'
  - name: sciplat-fe-module-luma-admin
    version: 0.3.12-6761-1
    repository: '@helm-virtual'
  - name: luma-registration
    version: 0.0.1-4560-1
    repository: '@helm-virtual'
  - name: datacore-frontend
    version: 1.17.0-19823427691-1-3effb17e
    repository: '@helm-virtual'
  - name: bioglyph-fe
    version: 0.0.1-016ab099
    repository: '@helm-virtual'
  - name: luma-mixologist-backend
    version: 0.9.0-5741-1
    repository: '@helm-virtual'
  - name: luma-svc-if-module
    version: 0.0.1-892-1
    repository: '@helm-virtual'
  - name: luma-ops-application-resources
    version: 0.2.0-6f9f9e55
    repository: '@helm-virtual'
  - name: app-service
    version: 1.17.0-19821046214-1-963b4c8f
    repository: '@helm-virtual'
    condition: app-service.enabled
  - name: luma-app-observer
    version: 0.0.1-51-1
    repository: '@helm-virtual'
  - name: luma-agent
    version: 0.0.4-307-1
    repository: '@helm-virtual'
    condition: luma-agent.enabled
  - name: luma-ontology
    version: 0.0.1-354-1
    repository: '@helm-virtual'
    condition: luma-ontology.enabled
  - name: luma-app-library
    version: 1.0.2-78-1
    repository: '@helm-virtual'
  - name: datacore-gateway
    version: 1.17.0-19821046214-1-963b4c8f
    repository: '@helm-virtual'
