global:
  containerRegistry: ''
  imagePullSecret: ''
  ingressHostName: ''
  ingressClassName: ''
e2etest:
  luma-datacore-automation: 1.17.0-19130716750-1-c99e4b34
  luma-platform-automation: 1.0.6252
luma-agent:
  enabled: false
  auth:
    mode: internal
  backend:
    dapr:
      enabled: true
  standalone: false
  fullnameOverride: luma-agent
app-service:
  enabled: false
luma-ontology:
  enabled: false
