global:
  containerRegistry: ''
  imagePullSecret: ''
  ingressHostName: ''
  ingressClassName: ''
e2etest:
  luma-datacore-automation: 1.17.0-19272748998-1-d79e8978
  luma-platform-automation: 1.0.6328
luma-agent:
  enabled: false
  auth:
    mode: internal
  backend:
    dapr:
      enabled: true
  standalone: false
  fullnameOverride: luma-agent
app-service:
  enabled: false
luma-ontology:
  enabled: false
