global:
  containerRegistry: ''
  imagePullSecret: ''
  ingressHostName: ''
  ingressClassName: ''
luma-agent:
  enabled: false
  auth:
    mode: internal
  backend:
    dapr:
      enabled: true
  standalone: false
  fullnameOverride: luma-agent
app-service:
  enabled: false
e2etest:
  luma-datacore-automation: 1.17.1-release-26-01-0-21000932813-1-121a6f9d
  luma-platform-automation: 1.0.7429-release-26-01-0
