name: Package and Publish Helm Chart
run-name: ${{ github.actor }} invoked publication 🚀
on: 
    push:
      tags:
        - '*'
jobs:
  Package-Publish-Chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up helm repository
        run: | 
          helm repo add helm-virtual https://dtxlabs.jfrog.io/artifactory/api/helm/helm-virtual \
          --username ci-user-github-helm-write --password ${{ secrets.JFROG_HELM_TOKEN }}
      - name: Running Helm Package and Publish Script
        run: ./.github/scripts/helm.sh ${{ github.ref_name }} 
        shell: bash
        env:
          SOME_MESSAGE: "Welcome to the file"