name: Package and Publish Helm Chart
run-name: ${{ github.actor }} invoked publication 🚀
on: 
    push:
      tags:
        - '*'
jobs:
  Package-Publish-Chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up helm repository
        run: | 
          echo ${{ secrets.JFROG_HELM_READ }} | helm repo add helm-virtual https://dtxlabs.jfrog.io/artifactory/api/helm/helm-virtual \
            --username ci-users-github-helm-read --password-stdin
      - name: Package Helm Chart
        run: ./.github/scripts/helm.sh ${{ github.ref_name }} 
        shell: bash
      - uses: jfrog/setup-jfrog-cli@v3
        env: 
          JF_URL: https://dtxlabs.jfrog.io
          JF_ACCESS_TOKEN: ${{ secrets.JFROG_HELM_WRITE }}
      - name: Publishing Helm Chart
        run: |
            jf rt u zebra-sdlc-rollup-${{ github.ref_name }}.tgz zebra-releases
      - name: Create a release in Octopus Deploy 🐙
        uses: OctopusDeploy/create-release-action@v3
        with:
          server: ${{ secrets.OCTOPUS_SERVER }}
          api_key: ${{ secrets.OCTOPUS_API_KEY }}
          space: 'Default'
          project: 'DataGalaxy'
          release_number: ${{ github.ref_name }}
          package_version: ${{ github.ref_name }}
      