name: Tagged Release
run-name: Tagged Release for ${{ github.actor }}
on: 
  push:
    tags:
      - '*'
env:
  OCTOPUS_SPACE: "Luma Platform"
  OCTOPUS_PROJECT: "Luma Platform App"

jobs:
  Package-Publish-Chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Establishing Release Channel Name and Version
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          if [[ "$TAG_NAME" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            DEPLOYMENT_CHANNEL='Release'
            echo "LUMA_VERSION=$TAG_NAME" >> "$GITHUB_ENV"
          elif [[ "$TAG_NAME" =~ ^[0-9]+\.[0-9]+\.[0-9]+\-.+$ ]]; then
            DEPLOYMENT_CHANNEL='Pre Release'
            echo "LUMA_VERSION=${TAG_NAME}" >> "$GITHUB_ENV"
          else
            echo 'The tag used is not a valid release sem.ver'
            exit 1
          fi
          
          echo "OCTOPUS_CHANNEL=$DEPLOYMENT_CHANNEL" >> "$GITHUB_ENV"
        shell: bash

      - name: Setting up helm repository
        env: 
          JFROG_TOKEN: ${{ secrets.DATAGALAXY_GHA_HELM_READ }}
        run: | 
          echo "$JFROG_TOKEN" | helm repo add helm-virtual https://dtxlabs.jfrog.io/artifactory/api/helm/helm-virtual \
            --username gha_helm_read --password-stdin

      - name: Package Helm Chart
        shell: bash
        run: ./.github/scripts/helm.sh "$LUMA_VERSION"

      - uses: jfrog/setup-jfrog-cli@v3
        env: 
          JF_URL: https://dtxlabs.jfrog.io
          JF_ACCESS_TOKEN: ${{ secrets.DATAGALAXY_GHA_ZEBRARELEASES_READWRITE }}

      - name: Publishing Helm Chart
        shell: bash
        run: |
            jf rt u "zebra-sdlc-rollup-$LUMA_VERSION.tgz" zebra-releases

      - name: Create a release in Octopus Deploy 🐙
        uses: OctopusDeploy/create-release-action@v3
        with:
          server: ${{ secrets.OCTOPUS_SERVER }}
          api_key: ${{ secrets.DATAGALAXY_GHA_OCTOPUS_RELEASE_TOKEN }}
          space: ${{ env.OCTOPUS_SPACE }}
          project: ${{ env.OCTOPUS_PROJECT }}
          channel: ${{ env.OCTOPUS_CHANNEL }}
          git_ref: 'refs/heads/main'
          release_number: ${{ env.LUMA_VERSION }}
          packages: 'zebra-sdlc-rollup:${{ env.LUMA_VERSION }}'

      - name: Push build info 🐙
        uses: OctopusDeploy/push-build-information-action@v3
        with:
          server: ${{ secrets.OCTOPUS_SERVER }}
          api_key: ${{ secrets.DATAGALAXY_GHA_OCTOPUS_RELEASE_TOKEN }}
          space: ${{ env.OCTOPUS_SPACE }}
          version: ${{ env.LUMA_VERSION }}
          packages: 'zebra-sdlc-rollup'

      - name: Clean up helm login
        if: always()
        shell: bash
        run: helm repo remove helm-virtual
